# Generated by Django 5.2.3 on 2025-08-05 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='address',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(default=1, upload_to='Upload/Picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='occupation',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='opinion',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
