# Generated by Django 5.2.3 on 2025-08-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_testimonial_address_testimonial_img_testimonial_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
