# Generated by Django 5.2.3 on 2025-08-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_testimonial_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='img',
            field=models.ImageField(upload_to='Picture'),
        ),
    ]
