# Generated by Django 5.2.3 on 2025-08-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_alter_testimonial_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField()),
                ('website', models.CharField(max_length=100)),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Aboutextra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.FloatField()),
                ('degree', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('freelancer', models.CharField(max_length=150)),
            ],
        ),
    ]
