# Generated by Django 5.2.3 on 2025-08-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_about_aboutextra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutextra',
            name='age',
            field=models.IntegerField(),
        ),
    ]
