# Generated by Django 5.2.3 on 2025-08-05 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='heroname',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
