# Generated by Django 5.2.3 on 2025-08-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_hero_heroname'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='favapple',
            field=models.ImageField(default=1, upload_to='Picture'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hero',
            name='favicon',
            field=models.ImageField(default=1, upload_to='Picture'),
            preserve_default=False,
        ),
    ]
