# Generated by Django 5.2.3 on 2025-08-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_hero_favapple_hero_favicon'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='file',
            field=models.FileField(default=1, upload_to='Picture'),
            preserve_default=False,
        ),
    ]
