# Generated by Django 5.2.3 on 2025-08-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_hero_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Picture'),
        ),
    ]
