# Generated by Django 5.2.3 on 2025-08-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_alter_hero_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='Picture')),
            ],
        ),
        migrations.RemoveField(
            model_name='hero',
            name='file',
        ),
    ]
